### ISSUE TITLE
Sponsors page has been removed, but it is being used in hame.dart, which is causing errors.

### ISSUE THREAD

**Issue by puneethkanna** [smaranjitghose/girlscript_app#107]

**Comment by kamal-kaur04** [comment]
Hello @puneethkanna Can I take this issue?

**Comment by puneethkanna** [comment]
> Hello @puneethkanna Can I take this issue?

Sure!, work on it.

**Comment by kamal-kaur04** [comment]
@puneethkanna I am getting these warnings when I executed the command **" git add ."** Kindly tell if this is a normal behavior?
Thank you.

![image](https://user-images.githubusercontent.com/38219887/76194510-54cbe680-620c-11ea-9595-48120bdee666.png)

**Comment by kamal-kaur04** [comment]
@puneethkanna I changed the access mode of android-gradlew because due to that I was notable to build the project. But it has changed many files. I come to know about it when I committed my changes to resolve the issue. I am attaching the file of logs. Please suggest mewhat to do now?

[gnotes.pdf](https://github.com/smaranjitghose/girlscript_app/files/4305497/gnotes.pdf)
